version: 2
jobs:
  build:
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: "./scripts/build_docker.sh"
      - run:
          name: Run Tests
          command: "./scripts/run_tests.sh"
      - run:
          name: Run Mutation Tests
          command: "./scripts/run_infection.sh"
